#if !canImport(ObjectiveC)
import XCTest

extension SysctlTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SysctlTests = [
        ("testHardwareLookup", testHardwareLookup),
        ("testKernelLookup", testKernelLookup),
        ("testNetwork", testNetwork),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SysctlTests.__allTests__SysctlTests),
    ]
}
#endif
