#if !canImport(ObjectiveC)
import XCTest

extension AccessTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AccessTests = [
        ("testReading", testReading),
        ("testWriting", testWriting),
    ]
}

extension NameGenerationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NameGenerationTests = [
        ("testHardwareNamespace", testHardwareNamespace),
        ("testKernelNamespace", testKernelNamespace),
        ("testNetworkingNamespace", testNetworkingNamespace),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AccessTests.__allTests__AccessTests),
        testCase(NameGenerationTests.__allTests__NameGenerationTests),
    ]
}
#endif
