#if !canImport(ObjectiveC)
import XCTest

extension SysCtlTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SysCtlTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SysCtlTests.__allTests__SysCtlTests),
    ]
}
#endif
